// Copyright 2025 Michael Hoopmann
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using Nova.Data;
using Nova.Io.Read;

namespace TestNova
{
  // TEST-2: the pre-existing suite only exercised the readers end-to-end against one real
  // acquisition (AngioNeuro4) and asserted aggregate counts. These tests use small, hand-built
  // mzML/mzXML fixtures (Test/Files/NovaTestFixture.*, generated by
  // scripts/gen_fixtures.py-equivalent logic - see the file header comment there is none, the
  // fixtures are static, checked-in files) with 4 known spectra (MS1/MS2, alternating FTMS and
  // ITMS filter strings) so individual field values - not just scan counts - can be asserted.
  // MzMLReader/MzXMLReader are `internal`, so this goes through the public FileReader facade,
  // same as the pre-existing suite.
  [TestClass]
  public sealed class TestNovaIOFixtures
  {
    private readonly string dataFilePathMzML;
    private readonly string dataFilePathMzXML;
    private readonly string dataFilePathMzMLMalformed;
    private readonly string dataFilePathMzXMLMalformed;
    public TestContext testContext { get; set; }

    public TestNovaIOFixtures(TestContext context)
    {
      testContext = context;
      string filesDir = TestFilePaths.GetFilesDirectory();
      dataFilePathMzML = Path.Combine(filesDir, "NovaTestFixture.mzML");
      dataFilePathMzXML = Path.Combine(filesDir, "NovaTestFixture.mzXML");
      dataFilePathMzMLMalformed = Path.Combine(filesDir, "NovaTestFixtureMalformed.mzML");
      dataFilePathMzXMLMalformed = Path.Combine(filesDir, "NovaTestFixtureMalformed.mzXML");
    }

    [TestMethod]
    public void MzML_OpenAndScanCount()
    {
      testContext.WriteLine("Verifies OpenSpectrumFile succeeds on the mzML fixture and reports the correct scan count/range/max retention time.");
      FileReader reader = new FileReader();
      Assert.IsTrue(reader.OpenSpectrumFile(dataFilePathMzML));
      Assert.AreEqual(4, reader.ScanCount);
      Assert.AreEqual(1, reader.FirstScan);
      Assert.AreEqual(4, reader.LastScan);
      Assert.AreEqual(1.00, reader.MaxRetentionTime, 1e-9);
    }

    [TestMethod]
    public void MzML_MsLevelTally()
    {
      testContext.WriteLine("Verifies scanning the mzML fixture end to end tallies 2 MS1 and 2 MS2 spectra.");
      FileReader reader = new FileReader();
      int ms1 = 0, ms2 = 0, ms3 = 0;
      Spectrum spec = reader.ReadSpectrum(dataFilePathMzML);
      while (spec.ScanNumber > 0)
      {
        if (spec.MsLevel == 1) ms1++;
        else if (spec.MsLevel == 2) ms2++;
        else if (spec.MsLevel == 3) ms3++;
        spec = reader.ReadSpectrum();
      }
      Assert.AreEqual(2, ms1);
      Assert.AreEqual(2, ms2);
      Assert.AreEqual(0, ms3);
    }

    [TestMethod]
    public void MzML_Ms1Spectrum_FieldsAndBinaryData()
    {
      testContext.WriteLine("Verifies scan-level fields and decoded 64-bit m/z/intensity data points for an MS1 mzML spectrum.");
      FileReader reader = new FileReader();
      Spectrum spec = reader.ReadSpectrum(dataFilePathMzML, 1);

      Assert.AreEqual(1, spec.ScanNumber);
      Assert.AreEqual(1, spec.MsLevel);
      Assert.AreEqual("FTMS", spec.Analyzer);
      Assert.AreEqual(0.50, spec.RetentionTime, 1e-9);
      Assert.AreEqual(4500.0, spec.TotalIonCurrent, 1e-9);
      Assert.AreEqual(3, spec.Count);
      Assert.AreEqual(400.1, spec.DataPoints[0].Mz, 1e-9);
      Assert.AreEqual(1000.0, spec.DataPoints[0].Intensity, 1e-9);
      Assert.AreEqual(450.2, spec.DataPoints[1].Mz, 1e-9);
      Assert.AreEqual(2000.0, spec.DataPoints[1].Intensity, 1e-9);
      Assert.AreEqual(500.3, spec.DataPoints[2].Mz, 1e-9);
      Assert.AreEqual(1500.0, spec.DataPoints[2].Intensity, 1e-9);
    }

    [TestMethod]
    public void MzML_Ms2Spectrum_PrecursorFields()
    {
      testContext.WriteLine("Verifies precursor fields (isolation m/z/width, monoisotopic m/z, charge, fragmentation method) for an MS2 mzML spectrum.");
      FileReader reader = new FileReader();
      Spectrum spec = reader.ReadSpectrum(dataFilePathMzML, 2);

      Assert.AreEqual(2, spec.ScanNumber);
      Assert.AreEqual(2, spec.MsLevel);
      Assert.AreEqual(1, spec.PrecursorMasterScanNumber);
      Assert.AreEqual(1, spec.Precursors.Count);
      Assert.AreEqual(500.25, spec.Precursors[0].IsolationMz, 1e-9);
      Assert.AreEqual(2.0, spec.Precursors[0].IsolationWidth, 1e-9);
      Assert.AreEqual(500.2, spec.Precursors[0].MonoisotopicMz, 1e-9);
      Assert.AreEqual(2, spec.Precursors[0].Charge);
      Assert.AreEqual(FramentationType.HCD, spec.Precursors[0].FramentationMethod);
    }

    [TestMethod]
    public void MzML_Ms2ItmsSpectrum_NonExPath_IsCorrect()
    {
      // Regression test for BUG-3 (docs/known-issues.md, fixed 2026-08-19):
      // MzMLReader.ProcessCvParam's non-ext (Spectrum) branch for an "ITMS"-containing filter
      // string used to set Analyzer to the literal "OTMS" instead of "ITMS" - a copy/paste
      // typo. This test originally pinned that buggy value as a characterization test; now
      // that the typo is fixed, it asserts the correct value so a regression trips this test.
      testContext.WriteLine("Regression test for BUG-3: verifies the non-Ex (Spectrum) read path sets Analyzer to \"ITMS\", not the old \"OTMS\" typo.");
      FileReader reader = new FileReader();
      Spectrum spec = reader.ReadSpectrum(dataFilePathMzML, 2);
      Assert.AreEqual("ITMS", spec.Analyzer);
    }

    [TestMethod]
    public void MzML_Ms2ItmsSpectrum_ExPath_IsCorrect()
    {
      testContext.WriteLine("Verifies the Ex (SpectrumEx) read path correctly sets Analyzer to \"ITMS\" for an ion-trap filter string.");
      FileReader reader = new FileReader();
      SpectrumEx spec = reader.ReadSpectrumEx(dataFilePathMzML, 2);
      Assert.AreEqual("ITMS", spec.Analyzer);
    }

    [TestMethod]
    public void MzML_MalformedFile_OpenDoesNotThrow()
    {
      // Regression test for BUG-8 (docs/known-issues.md, fixed 2026-08-19):
      // MzMLReader.Open() catches the missing-index exception and returns false;
      // FileReader.OpenSpectrumFile now propagates that instead of discarding it, so no
      // exception escapes and the caller can tell from the return value alone that the open
      // failed.
      testContext.WriteLine("Regression test for BUG-8: verifies OpenSpectrumFile returns false (not true) on an mzML file with no index block.");
      FileReader reader = new FileReader();
      bool opened = reader.OpenSpectrumFile(dataFilePathMzMLMalformed);
      Assert.IsFalse(opened);
      Assert.AreEqual(0, reader.ScanCount);

      Spectrum spec = reader.ReadSpectrum(dataFilePathMzMLMalformed);
      Assert.AreEqual(0, spec.ScanNumber);
      Assert.AreEqual(0, spec.Count);
    }

    [TestMethod]
    public void MzXML_OpenAndScanCount()
    {
      testContext.WriteLine("Verifies OpenSpectrumFile succeeds on the mzXML fixture and reports the correct scan count/range/max retention time.");
      FileReader reader = new FileReader();
      Assert.IsTrue(reader.OpenSpectrumFile(dataFilePathMzXML));
      Assert.AreEqual(4, reader.ScanCount);
      Assert.AreEqual(1, reader.FirstScan);
      Assert.AreEqual(4, reader.LastScan);
      Assert.AreEqual(1.00, reader.MaxRetentionTime, 1e-9);
    }

    [TestMethod]
    public void MzXML_MsLevelTally()
    {
      testContext.WriteLine("Verifies scanning the mzXML fixture end to end tallies 2 MS1 and 2 MS2 spectra.");
      FileReader reader = new FileReader();
      int ms1 = 0, ms2 = 0, ms3 = 0;
      Spectrum spec = reader.ReadSpectrum(dataFilePathMzXML);
      while (spec.ScanNumber > 0)
      {
        if (spec.MsLevel == 1) ms1++;
        else if (spec.MsLevel == 2) ms2++;
        else if (spec.MsLevel == 3) ms3++;
        spec = reader.ReadSpectrum();
      }
      Assert.AreEqual(2, ms1);
      Assert.AreEqual(2, ms2);
      Assert.AreEqual(0, ms3);
    }

    [TestMethod]
    public void MzXML_Ms1Spectrum_FieldsAndBinaryData()
    {
      testContext.WriteLine("Verifies scan-level fields and decoded 64-bit m/z/intensity data points (big-endian) for an MS1 mzXML spectrum.");
      FileReader reader = new FileReader();
      Spectrum spec = reader.ReadSpectrum(dataFilePathMzXML, 1);

      Assert.AreEqual(1, spec.ScanNumber);
      Assert.AreEqual(1, spec.MsLevel);
      Assert.AreEqual(0.50, spec.RetentionTime, 1e-6);
      Assert.AreEqual(4500.0, spec.TotalIonCurrent, 1e-9);
      Assert.AreEqual(3, spec.Count);
      Assert.AreEqual(400.1, spec.DataPoints[0].Mz, 1e-9);
      Assert.AreEqual(1000.0, spec.DataPoints[0].Intensity, 1e-9);
      Assert.AreEqual(450.2, spec.DataPoints[1].Mz, 1e-9);
      Assert.AreEqual(2000.0, spec.DataPoints[1].Intensity, 1e-9);
      Assert.AreEqual(500.3, spec.DataPoints[2].Mz, 1e-9);
      Assert.AreEqual(1500.0, spec.DataPoints[2].Intensity, 1e-9);
    }

    [TestMethod]
    public void MzXML_Ms2Spectrum_PrecursorFields()
    {
      testContext.WriteLine("Verifies precursor fields (isolation m/z, charge, fragmentation method) for an MS2 mzXML spectrum.");
      FileReader reader = new FileReader();
      Spectrum spec = reader.ReadSpectrum(dataFilePathMzXML, 2);

      Assert.AreEqual(2, spec.ScanNumber);
      Assert.AreEqual(2, spec.MsLevel);
      Assert.AreEqual(1, spec.PrecursorMasterScanNumber);
      Assert.AreEqual(1, spec.Precursors.Count);
      Assert.AreEqual(500.25, spec.Precursors[0].IsolationMz, 1e-9);
      Assert.AreEqual(2, spec.Precursors[0].Charge);
      Assert.AreEqual(FramentationType.HCD, spec.Precursors[0].FramentationMethod);
    }

    [TestMethod]
    public void MzXML_MalformedFile_OpenDoesNotThrow()
    {
      // Regression test for BUG-8 (docs/known-issues.md, fixed 2026-08-19): see the mzML
      // counterpart above for the full explanation.
      testContext.WriteLine("Regression test for BUG-8: verifies OpenSpectrumFile returns false (not true) on an mzXML file with no index block.");
      FileReader reader = new FileReader();
      bool opened = reader.OpenSpectrumFile(dataFilePathMzXMLMalformed);
      Assert.IsFalse(opened);
      Assert.AreEqual(0, reader.ScanCount);

      Spectrum spec = reader.ReadSpectrum(dataFilePathMzXMLMalformed);
      Assert.AreEqual(0, spec.ScanNumber);
      Assert.AreEqual(0, spec.Count);
    }
  }
}
