# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "Reorg4Helios" ]
  pull_request:
    branches: [ "Reorg4Helios" ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup RawFileReader
      uses: actions/checkout@main
      with:
        path: .\RawFileReader
        repository: thermofisherlsms/RawFileReader
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2

    - name: Point NuGet to RawFileReader
      run: nuget add source .\RawFileReader\Libs\NetCore\Net8

    - name: Everything NuGet sucks
      run: set NUGET_PACKAGES="D:\a\RawFileReader\Libs\NetCore\Net8"
        
    - name: Restore dependencies
      run: dotnet restore .\Nova\Nova.sln
      
    - name: Build
      run: dotnet build Nova\Nova.sln --no-restore --framework net482 --configuration Release --arch x64 /p:Platform="x64"
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
